image: maven:3.6-jdk-8

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script: mvn $MAVEN_CLI_OPTS -Dmaven.test.skip=true package
  artifacts:
    paths:
      - target/*jar
    expire_in: 1 week

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  image: cibuilds/github:0.12
  dependencies:
    - build
  script:
    # ghr doesn't support artibrary globs
    - rm -rf target/artifacts && mkdir -p target/artifacts && cp target/*jar target/artifacts
    - ghr
        -n "BlockChyp Java SDK ${CI_COMMIT_TAG##*-}"
        -u blockchyp
        -r blockchyp-java -c "${CI_COMMIT_SHA}"
        -recreate
        "${CI_COMMIT_TAG}"
        target/artifacts
  only:
    - tags
