version: 1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout

      - restore_cache:
          keys:
            - mvn-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: mvn-{{ checksum "pom.xml" }}

      - run:
          name: Build
          command: make build

      - run:
          name: Test
          command: make test

      - store_test_results:
          path: target/surefire-reports

      - persist_to_workspace:
          root: ./target
          paths:
            - ./*

  publish:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout

      - attach_workspace:
          at: ./target

      - run: ./.circleci/import-gpg-key.sh

      - run:
          name: Publish
          command: make publish

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
